name: .NET

on:
  push:
    branches: [ net9 ]
  pull_request:
    branches: [ net9 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore AsyncKeyedLock.TestsNet8
      
    - name: Build
      run: dotnet build AsyncKeyedLock.TestsNet8 --no-restore --configuration Release
      
    - name: Test
      run: dotnet test AsyncKeyedLock.TestsNet8 --no-restore --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --settings coverlet.runsettings
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore AsyncKeyedLock.Tests
      
    - name: Build
      run: dotnet build AsyncKeyedLock.Tests --no-restore --configuration Release
      
    - name: Test
      run: dotnet test AsyncKeyedLock.Tests --no-restore --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --settings coverlet.runsettings
      
    - name: Coverage
      uses: codecov/codecov-action@v3
