name: .NET

on:
  push:
    branches: [ net9 ]
  pull_request:
    branches: [ net9 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            8.0.x
            9.0.x
        dotnet-quality: 'preview'
        
    - name: Restore dependencies
      run: dotnet restore --locked-mode
      
    - name: Build
      with:
        dotnet-version: '8.0.x'
        dotnet-quality: 'preview'
      run: dotnet build AsyncKeyedLock.TestsNet8 --no-restore --configuration Release
      
    - name: Test
      with:
        dotnet-version: '8.0.x'
        dotnet-quality: 'preview'
      run: dotnet test AsyncKeyedLock.TestsNet8 --no-restore --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --settings coverlet.runsettings
      
    - name: Build
      with:
        dotnet-version: '9.0.x'
        dotnet-quality: 'preview'  
      run: dotnet build AsyncKeyedLock.Tests --no-restore --configuration Release
      
    - name: Test
      with:
        dotnet-version: '9.0.x'
        dotnet-quality: 'preview'    
      run: dotnet test AsyncKeyedLock.Tests --no-restore --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --settings coverlet.runsettings
      
    - name: Coverage
      uses: codecov/codecov-action@v3
